<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_digibox</name>
   <tag></tag>
   <elementGuidId>a7a56ae5-6f53-4638-a82f-5d6a36f86086</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>    font-size: 14px;&#xd;
    --color-white: #fff;&#xd;
    --color-black: #000;&#xd;
    --promotion-color-primary: #FFA033;&#xd;
    --coupon-color-primary: #F2E8D5;&#xd;
    --coupon-color-regular: #F8F1E4;&#xd;
    --coupon-color-disabled: #F5F3EF;&#xd;
    --success-icon-color: #52C41A;&#xd;
    --checkbox-color-primary: #1e1e1e;&#xd;
    --checkbox-size: 20px;&#xd;
    --font-size-secondary-title: 20px;&#xd;
    --font-weight-regular: 400;&#xd;
    --border-color-regular: rgba(0, 0, 0, 0.12);&#xd;
    --border-color-default: var(--border-color-regular);&#xd;
    --border-color-lighter: rgba(0, 0, 0, 0.08);&#xd;
    --border-size-small: 1px;&#xd;
    --border-size-medium: 2px;&#xd;
    --border-small-default: 1px solid var(--border-color-default);&#xd;
    --border-medium-default: 2px solid var(--border-color-default);&#xd;
    --border-small-lighter: 1px solid var(--border-color-lighter);&#xd;
    --border-radius-default: 0px;&#xd;
    --border-radius-small: 2px;&#xd;
    --border-radius-medium: 4px;&#xd;
    --btn-color-primary: var(--theme-color-primary);&#xd;
    --btn-color-default: #1e1e1e;&#xd;
    --btn-color-pay: #990000;&#xd;
    --btn-color-pay-hover: #C1002D;&#xd;
    --btn-border-radius: var(--border-radius-medium);&#xd;
    --btn-mini-height: 28px;&#xd;
    --btn-mini-font-size: 12px;&#xd;
    --btn-small-height: 32px;&#xd;
    --btn-small-font-size: 14px;&#xd;
    --btn-large-height: 40px;&#xd;
    --btn-large-font-size: 16px;&#xd;
    --btn-font-color-hover: var(--btn-font-color);&#xd;
    --btn-border-color-hover: var(--btn-border-color);&#xd;
    --btn-background-color-hover: var(--btn-background-color);&#xd;
    --btn-font-color-active: var(--btn-border-color);&#xd;
    --btn-border-color-active: #c6e2ff;&#xd;
    --btn-background-color-active: #ecf5ff;&#xd;
    --btn-border-color-disabled: #a0cfff;&#xd;
    --btn-background-color-disabled: #a0cfff;&#xd;
    --btn-isplain-background-color: #fafafa;&#xd;
    --btn-isplain-font-color-hover: var(--btn-isplain-font-color);&#xd;
    --btn-isplain-border-color-hover: var(--btn-isplain-border-color);&#xd;
    --btn-isplain-background-color-hover: var(--btn-isplain-background-color);&#xd;
    --btn-isplain-font-color: var(--btn-border-color);&#xd;
    --btn-isplain-border-color: var(--btn-border-color);&#xd;
    --btn-isplain-font-color-active: #fff;&#xd;
    --btn-isplain-border-color-active: var(--btn-border-color);&#xd;
    --btn-isplain-background-color-active: var(--btn-border-color);&#xd;
    --checkbox-default-size: 16px;&#xd;
    --checkbox-default-icon-size: 4px;&#xd;
    --checkbox-accept-terms-font-size: var(--btn-small-font-size);&#xd;
    --checkbox-accept-terms-font-color: var(--font-color-primary);&#xd;
    --checkbox-accept-terms-a-font-color: var(--font-color-secondary);&#xd;
    --checkbox-accept-terms-a-text-decoration-color: var(--font-color-secondary);&#xd;
    --page-pc-margin: 20px;&#xd;
    --page-pc-padding: 20px;&#xd;
    --header-nav-pc-height: 38px;&#xd;
    --header-pc-height: calc( var(--header-logo-pc-height) + var(--header-nav-pc-height) + 20px);&#xd;
    --header-bottom-border: var(--border-small-default);&#xd;
    --header-nav-active-color: var(--color-black);&#xd;
    --header-icon-font-size: 20px;&#xd;
    --header-my-padding: 0;&#xd;
    --header-my-first-word-background-color: rgba(255, 255, 255, 0.35);&#xd;
    --header-my-first-word-font-color: #fff;&#xd;
    --header-my-first-word-font-size: 12px;&#xd;
    --header-my-first-word-font-weight: 400;&#xd;
    --header-my-first-word-background-width: 18px;&#xd;
    --header-my-first-word-background-height: 18px;&#xd;
    --header-my-first-word-border-radius: 50%;&#xd;
    --header-my-name-font-size: 12px;&#xd;
    --header-my-name-font-weight: 400;&#xd;
    --header-my-name-font-color: #fff;&#xd;
    --pdp-attr-active-color: var(--btn-font-color-active);&#xd;
    --pdp-attr-border: 1px solid var(--border-color-default);&#xd;
    --pdp-attr-active-border: 1px solid var(--pdp-attr-active-color);&#xd;
    --pdp-attr-width: 120px;&#xd;
    --pdp-attr-active--radius: 50%;&#xd;
    --pdp-attr-item-gap-width: 12px;&#xd;
    --pdp-ipi-font-size: 14px;&#xd;
    --pdp-attr-height: auto;&#xd;
    --pdp-left-width: 496px;&#xd;
    --pdp-right-width: auto;&#xd;
    --pdp-left-image-width: 496px;&#xd;
    --pdp-left-image-small-width: 88px;&#xd;
    --pdp-attr-item-active-color: var(--btn-background-color);&#xd;
    --pdp-attr-disabled-color: var(--font-color-regular);&#xd;
    --pdp-attr-disabled-border-color: var(--font-color-secondary);&#xd;
    --pdp-button-color: var(--btn-background-color);&#xd;
    --pdp-photo-zoom-border: 1px solid var(--color-black);&#xd;
    --cart--page-max-width: 916px;&#xd;
    --cart-sku-right-txt-align: right;&#xd;
    --cart-mobile-sku-info-txt-align: left;&#xd;
    --cart-sku-right-product-price-font-size: 14px;&#xd;
    --cart-sku-right-product-price-font-color: rgba(0, 0, 0, 0.45);&#xd;
    --cart-sku-right-product-price-line-height: 18px;&#xd;
    --cart-sku-right-product-price-font-weight: 300;&#xd;
    --cart-sku-right-product-price-text-decoration: line-through;&#xd;
    --cart-sku-right-price-font-size: 16px;&#xd;
    --cart-sku-right-price-font-weight: var(--font-weight-medium);&#xd;
    --store--left-width: 388px;&#xd;
    --store--left-bgcolor: #f6f6f6;&#xd;
    --store--font-primary: rgba($color: #000000, $alpha: 0.85);&#xd;
    --store--font-des: rgba($color: #000000, $alpha: 0.65);&#xd;
    --footer-padding-left-right: 108px;&#xd;
    --footer-font-mini: 12px;&#xd;
    --footer-right-width: 260px;&#xd;
    --footer-border-color: rgba(0, 0, 0, 0.08);&#xd;
    --footer-top-border: var(--border-small-default);&#xd;
    --footer-subscribe-border-color: #000;&#xd;
    --footer-nav-text-underline: underline;&#xd;
    --login-border-color: rgba(0, 0, 0, 0.08);&#xd;
    --login-erroor-box-background-color: #fff2f0;&#xd;
    --login-erroor-box-border-color: #ffccc6;&#xd;
    --login-button-color: var(--btn-border-color);&#xd;
    --login-font-color: var(--font-color-primary);&#xd;
    --login-button-background-disabled-color: rgba(0, 0, 0, 0.03);&#xd;
    --plp-filter-bg-color: #f5f5f7;&#xd;
    --plp-filter-bg-height: 64px;&#xd;
    --plp-sale-price-display: none;&#xd;
    --plp-min-price-display: block;&#xd;
    --order-nav-width: 280px;&#xd;
    --order-nav-bg-color: #fafafa;&#xd;
    --order-nav-name-font-color: var(--font-color-primary);&#xd;
    --order-nav-item-font-color: var(--font-color-primary);&#xd;
    --order-nav-item-text-decoration-color: var(--font-color-primary);&#xd;
    --order-nav-name-font-size: 18px;&#xd;
    --order-nav-item-font-size: 18px;&#xd;
    --order-nav-name-font-weight: 500;&#xd;
    --order-nav-item-font-weight: 400;&#xd;
    --order-status-tab-font-size: 14px;&#xd;
    --order-status-tab-font-color: var(--font-color-secondary);&#xd;
    --order-status-tab-active-font-color: var(--theme-color-primary);&#xd;
    --order-status-tab-active-bar-color: var(--theme-color-primary);&#xd;
    --order-select-delivery-button-font-color: #fff;&#xd;
    --order-select-delivery-button-backgroundColor: #000;&#xd;
    --order-select-delivery-button-border-color: #000;&#xd;
    --order-background-color: #fff;&#xd;
    --order-list-button-border-color: #111;&#xd;
    --order-list-button-width: 146px;&#xd;
    --order-list-item-padding: 16px;&#xd;
    --checkout-total-border-top: var(--border-small-lighter);&#xd;
    --landingpage-button-bg-color: #fff;&#xd;
    --landingpage-button-font-color: var(--font-color-primary);&#xd;
    --landingpage-button-border: 1px solid #ddd;&#xd;
    --landingpage-button-hover-font-color: #000;&#xd;
    --landingpage-button-hover-bg-color: #fff;&#xd;
    --landingpage-button-hover-border: 1px solid #ddd;&#xd;
    --header-nav-hover-background-color: rgba(0, 0, 0, 0.05);&#xd;
    --empty-font-size: var(--font-size-secondary-title);&#xd;
    --empty-max-width: var(--font-size-secondary-title);&#xd;
    --empty-content-min-width: var(--page-max-width);&#xd;
    --empty-content-min-height: 70vh;&#xd;
    --switch-lang-font-color: var(--font-color-primary);&#xd;
    --switch-lang-font-size: var(--font-size-defalut);&#xd;
    --switch-lang-background-color: #fff;&#xd;
    --switch-lang-hover-border-color: var(--btn-border-color);&#xd;
    --switch-lang-black-font-color: #fff;&#xd;
    --switch-lang-black-font-size: var(--font-size-defalut);&#xd;
    --switch-lang-black-background-color: #000;&#xd;
    --switch-lang-black-hover-border-color: #000;&#xd;
    --plp-no-more-text-color: var(--font-color-placeholder);&#xd;
    --plp-no-more-text-padding: 50px 0 50px 0;&#xd;
    --plp-no-more-text-border-top: 1px solid rgba(0, 0, 0, 0.06);&#xd;
    --plp-card-margin: 10px 0px 10px;&#xd;
    --plp-card-text-align: center;&#xd;
    --plp-card-product-name-margin: 10px 0 12px;&#xd;
    --plp-card-product-name-font-size: var(--font-size-primary);&#xd;
    --plp-card-product-name-font-color: var(--font-color-secondary);&#xd;
    --plp-card-product-name-font-weight: 300;&#xd;
    --plp-card-product-name-line-height: 20px;&#xd;
    --plp-card-product-name-height: 40px;&#xd;
    --plp-card-price-display: block;&#xd;
    --plp-card-product-price-padding: 0 7px;&#xd;
    --plp-card-product-price-display: block;&#xd;
    --plp-card-product-price-font-size: var(--font-size-primary);&#xd;
    --plp-card-product-price-font-color: var(--font-color-primary);&#xd;
    --plp-card-product-price-font-weight: 300;&#xd;
    --plp-card-product-price-line-height: 20px;&#xd;
    --plp-card-product-price-height: 20px;&#xd;
    --plp-card-product-price-text-decoration: line-through;&#xd;
    --plp-card-sale-price-font-size: var(--font-size-main);&#xd;
    --plp-card-sale-price-font-color: var(--font-color-price);&#xd;
    --plp-card-sale-price-font-weight: 400;&#xd;
    --plp-card-sale-price-line-height: 22px;&#xd;
    --plp-card-mobile-margin: 0 0 20px;&#xd;
    --plp-card-mobile-name-font-size: var(--font-size-defalut);&#xd;
    --plp-card-mobile-product-price-font-size: var(--font-size-defalut);&#xd;
    --plp-card-mobile-sale-price-font-size: var(--font-size-defalut);&#xd;
    --productprice-not-equal-saleprice-display: none;&#xd;
    --productprice-not-equal-minprice-display: block;&#xd;
    --plp-card-sale-label-width: 52px;&#xd;
    --plp-card-sale-label-height: 28px;&#xd;
    --plp-card-sale-label-bg-color: var(--promotion-color-primary);&#xd;
    --plp-card-sale-label-font-size: var(--btn-small-font-size);&#xd;
    --plp-card-sale-label-font-weight: var(--font-weight-medium);&#xd;
    --plp-card-sale-label-font-color: var(--color-white);&#xd;
    --plp-card-sale-label-line-height: 28px;&#xd;
    --plp-card-sale-label-left: 0;&#xd;
    --plp-card-sale-label-top: 0;&#xd;
    --plp-card-sale-label-bottom: auto;&#xd;
    --plp-card-sale-label-right: auto;&#xd;
    --plp-card-sale-label-display: block;&#xd;
    --plp-card-sale-label-transform: none;&#xd;
    --swiper-theme-color: #007aff;&#xd;
    --swiper-navigation-size: 44px;&#xd;
    --animate-duration: 1s;&#xd;
    --animate-delay: 1s;&#xd;
    --animate-repeat: 1;&#xd;
    --theme-color-primary: #cc0030;&#xd;
    --advertisement-background-color: rgb(213, 0, 50);&#xd;
    --header-font-color: #000;&#xd;
    --header-background-color: #fff;&#xd;
    --header-logo-pc-height: 60px;&#xd;
    --header-logo-mobile-height: 30px;&#xd;
    --footer-background-color: #fff;&#xd;
    --footer-font-color: #000;&#xd;
    --header-mobile-height: 60px;&#xd;
    --header-nav-active-underline: 2px solid var(--advertisement-background-color);&#xd;
    --header-sub-nav-active-underline-color: 2px solid var(--advertisement-background-color);&#xd;
    --font-color-primary: rgba(0, 0, 0, 0.8);&#xd;
    --font-color-secondary: rgba(0, 0, 0, 0.45);&#xd;
    --font-color-placeholder: rgba(0, 0, 0, 0.2);&#xd;
    --font-color-default: var(--font-color-primary);&#xd;
    --font-color-price: #d43232;&#xd;
    --font-color-error: #e40613;&#xd;
    --font-size-main: 18px;&#xd;
    --font-size-primary: 16px;&#xd;
    --font-size-secondary: 15px;&#xd;
    --font-size-defalut: 14px;&#xd;
    --font-size-info: 12px;&#xd;
    --font-weight-bold: 600;&#xd;
    --font-weight-medium: 500;&#xd;
    --font-color-regular: 400;&#xd;
    --font-weight-lighter: 300;&#xd;
    --font-weight-thin: 200;&#xd;
    --page-max-width: 1380px;&#xd;
    --btn-font-color: #fff;&#xd;
    --btn-background-color: #0071E3;&#xd;
    --btn-border-color: #0071E3;&#xd;
    --border-color-primary: #409EFF;&#xd;
    --checkbox-checked-background-color: #0071e3;&#xd;
    --input-small-height: 36px;&#xd;
    --input-medium-height: 44px;&#xd;
    --input-large-height: 56px;&#xd;
    --pdp-left-image-height: 655px;&#xd;
    -webkit-font-smoothing: antialiased;&#xd;
    font-weight: 300;&#xd;
    color: var(--header-font-color);&#xd;
    padding: 0;&#xd;
    font-family: inherit;&#xd;
    -webkit-tap-highlight-color: rgba(0,0,0,0);&#xd;
    box-sizing: border-box;&#xd;
    margin: 0;&#xd;
    word-break: break-word;&#xd;
    border: none;&#xd;
    height: 100%;&#xd;
    cursor: pointer;&#xd;
    object-fit: contain;&#xd;
    max-width: 100%;</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;page-view&quot;]/div/div[2]/div[1]/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
</WebElementEntity>
