<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon-akun</name>
   <tag></tag>
   <elementGuidId>d4349d08-b35c-4c35-bd99-b5c7a6d5b359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.iconfont.icon-account</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' iconfont ') and contains(concat(' ', normalize-space(@class), ' '), ' icon-account ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>dd672d0e-7f5d-4d7b-916e-9589177023cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iconfont icon-account</value>
      <webElementGuid>37332df0-7da6-4f6e-ab13-f72f4015c303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d2de2c96a6dbd4baf39bd5fce24e54e7</value>
      <webElementGuid>b93d2443-4970-4b39-a2c0-f08fd7c6d2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' iconfont ') and contains(concat(' ', normalize-space(@class), ' '), ' icon-account ')]</value>
      <webElementGuid>f5391f03-a280-4b7e-9ade-44c91e3a1ef6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' iconfont ') and contains(concat(' ', normalize-space(@class), ' '), ' icon-account ')]</value>
      <webElementGuid>837e8126-d748-4871-8de8-399d51c54c16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
