<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Order Details</name>
   <tag></tag>
   <elementGuidId>cc573cb3-51e5-4d3b-b404-7b0bd121960f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Order Details' or . = 'Order Details')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.el-button.el-button--default.el-button--small.gt-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Order Details&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8709adba-e1df-4664-ab5b-950bb48d4efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ae1b0cbd-cd0a-45a8-bf2b-99db3c5d2878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button--default el-button--small gt-button</value>
      <webElementGuid>95de3115-55ff-4f88-967c-f6fc69f49538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>937bb600-4b88-40d2-92a1-794e07d22164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Order Details</value>
      <webElementGuid>e38ee10b-74e2-4156-9008-8a7bec417057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;gt-order-page page-view__child&quot;]/div[@class=&quot;sp-order&quot;]/div[@class=&quot;sp-order-right&quot;]/div[1]/section[@class=&quot;sp-order__child&quot;]/div[@class=&quot;sp-order-page&quot;]/div[@class=&quot;sp-lazy-scroll&quot;]/div[@class=&quot;sp-scroll-loading&quot;]/div[@class=&quot;gt-skeleton&quot;]/div[@class=&quot;sp-order-list&quot;]/div[@class=&quot;sp-order-list-item&quot;]/div[@class=&quot;sp-order-list-item__btn&quot;]/div[@class=&quot;btns&quot;]/button[@class=&quot;el-button el-button--default el-button--small gt-button&quot;]</value>
      <webElementGuid>0dee53e4-6372-4676-83d3-99fe1cd7ee11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>36354fe0-cc29-49ea-844e-8bbba845bf4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div[3]/div/div[2]/div/section/div/div/div/div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>07a7ea7d-36ce-4542-a84d-96eb4e42f66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Status: Paid'])[1]/following::button[1]</value>
      <webElementGuid>de8a67ac-8f1a-4890-a1da-40120f9efe84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Status: PROCESSING'])[1]/following::button[1]</value>
      <webElementGuid>c22e1286-a3e6-4619-8e89-cd00e179cfd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$ 430'])[1]/preceding::button[1]</value>
      <webElementGuid>d8064579-3dbe-44e1-8661-068ba2291718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>3376cc72-e1c0-414c-aa6c-4bbbfe638d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Order Details' or . = 'Order Details')]</value>
      <webElementGuid>f9f7a7a8-a83a-4926-b0bb-f13aa54e089c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
