<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Checkout_Payment</name>
   <tag></tag>
   <elementGuidId>9975ca66-b31d-45cb-9126-d709e7542fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'page-checkout_right_top_custom')]//button[.//span[contains(text(),'Checkout')]]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.el-button.action-btn--onpage.el-button--primary.el-button--large.gt-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Checkout&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>796a4ae6-6957-47c2-957d-8ecfb09ecafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>primary</value>
      <webElementGuid>f65665fc-8e94-4df4-85d3-625491270cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button action-btn--onpage el-button--primary el-button--large gt-button</value>
      <webElementGuid>1da4380f-38c9-428d-91d8-6ec975b0bc46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>d43faaf5-971a-43cd-bffb-8949ac667ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Checkout
        </value>
      <webElementGuid>6a4de8ab-1de6-4bbc-a8de-313c29d2dfba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-view&quot;)/div[@class=&quot;gt-layout page-layout_pc&quot;]/div[@class=&quot;page-view__child&quot;]/section[@class=&quot;page-checkout&quot;]/div[@class=&quot;right&quot;]/section[@class=&quot;right-container&quot;]/div[@class=&quot;page-checkout_right_top_custom&quot;]/button[@class=&quot;el-button action-btn--onpage el-button--primary el-button--large gt-button&quot;]</value>
      <webElementGuid>eb796817-1dfb-46d1-9fdc-7dd4e78bd33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='primary'])[4]</value>
      <webElementGuid>068f87b4-5544-449b-9af5-783e660db728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-view']/div/div[3]/section/div[2]/section/div/button</value>
      <webElementGuid>13b975cf-b6ed-450b-bc66-024af970c9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About 3-7 working days'])[1]/following::button[1]</value>
      <webElementGuid>8a9233c9-4c16-4770-b111-72468df25e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coupon (0 available)'])[1]/preceding::button[1]</value>
      <webElementGuid>37ece9ea-a378-411f-b094-05f53829d352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/section/div/button</value>
      <webElementGuid>05a3f9a4-f2a8-4e47-8738-2208c9ba4350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'primary' and (text() = '
          Checkout
        ' or . = '
          Checkout
        ')]</value>
      <webElementGuid>cbf2dca1-3edc-481b-8239-e8322bd15c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
